
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 12 17:28:00 CST 2015
//----------------------------------------------------

package operacional;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int llaveC = 4;
  public static final int word = 11;
  public static final int div = 10;
  public static final int llaveA = 3;
  public static final int coma = 5;
  public static final int num = 12;
  public static final int menos = 8;
  public static final int EOF = 0;
  public static final int colon = 2;
  public static final int dcomilla = 6;
  public static final int error = 1;
  public static final int por = 9;
  public static final int mas = 7;
}

